import { convertFileSrc } from "@tauri-apps/api/core";

/**
 * Bundled sounds and icons, referenced as `preset:<id>` so a preset survives
 * the trip through the command line (`--notify '{"sound":"preset:chime"}'`)
 * and is only resolved to a URL when a notification is rendered.
 */
export const PRESET_PREFIX = "preset:";

export interface Preset {
  id: string;
  label: string;
  /** Path below `public/`, served from the app's root in dev and in bundles. */
  url: string;
}

function preset(kind: "sounds" | "icons", id: string, label: string, extension: string): Preset {
  return { id, label, url: `/presets/${kind}/${id}.${extension}` };
}

/** Generated by tools/generate-sound-presets.py. */
export const SOUND_PRESETS: Preset[] = [
  preset("sounds", "chime", "Chime", "wav"),
  preset("sounds", "ping", "Ping", "wav"),
  preset("sounds", "alert", "Alert", "wav"),
  preset("sounds", "success", "Success", "wav"),
  preset("sounds", "error", "Error", "wav"),
];

export const ICON_PRESETS: Preset[] = [
  preset("icons", "info", "Info", "svg"),
  preset("icons", "success", "Success", "svg"),
  preset("icons", "warning", "Warning", "svg"),
  preset("icons", "error", "Error", "svg"),
  preset("icons", "message", "Message", "svg"),
  preset("icons", "bell", "Bell", "svg"),
];

export function isPreset(value: string): boolean {
  return value.startsWith(PRESET_PREFIX);
}

export function presetRef(id: string): string {
  return `${PRESET_PREFIX}${id}`;
}

function findPreset(presets: Preset[], value: string): Preset | undefined {
  return presets.find((entry) => presetRef(entry.id) === value);
}

/**
 * Turns the `icon`/`sound` value of a notification into something a webview
 * can load: a bundled preset, a URL passed through untouched, or a local file
 * path wrapped in the asset protocol (a bare path is not loadable otherwise).
 */
function resolve(presets: Preset[], value: string | undefined | null): string | undefined {
  const trimmed = value?.trim();
  if (!trimmed) return undefined;

  if (isPreset(trimmed)) return findPreset(presets, trimmed)?.url;
  // file:// URLs are blocked in the webview just like bare paths are, so they
  // take the same asset-protocol route.
  if (/^file:\/\//i.test(trimmed)) return convertFileSrc(decodeURI(trimmed.slice("file://".length)));
  if (/^[a-z][a-z0-9+.-]*:\/\//i.test(trimmed) || trimmed.startsWith("data:")) return trimmed;
  return convertFileSrc(trimmed);
}

export function resolveSound(value: string | undefined | null): string | undefined {
  return resolve(SOUND_PRESETS, value);
}

export function resolveIcon(value: string | undefined | null): string | undefined {
  return resolve(ICON_PRESETS, value);
}
